
remote_theme: mmistakes/minimal-mistakes@4.17.2
plugins:
- jekyll-include-cache
locale: "en-US"
title: "Research Work and Trips"
name: "Franklyn Dunbar"
description: "This page highlights my efforts in academic research and climbing trips"
url: "https://frigusgulo.github.io"
search: true
logo: "/Assets/Images/headshot.jpg"
author:
        name: "Franklyn Dunbar"
        avatar: "/Assets/Images/headshot.jpg"
defaults:
        # _Pages
        -scope:
                path: "/pages"
                type: pages
        values:
                layout: single
                author_profile: true
defaults:
        #_Posts
        -dscope:
                path: "/posts"
                type: posts
        values:
                layout: single
                author_profile: true
                read_time: true
                comments: true
                share: true
                related: true
        paginate: 5
        paginate_path: /page:num/
include:
        -_Pages
        -_data
github: [metadata]
