
remote_theme: mmistakes/minimal-mistakes@4.17.2
plugins:
- jekyll-include-cache
locale: "en-US"
title: "My Academic Webpage"
name: "Franklyn Dunbar"
description: "Research and Trips"
url: "https://frigusgulo.github.io"
search: true
logo: "/Assets/Images/headshot.jpg"
author:
        name: "Franklyn Dunbar"
        avatar: "/Assets/Images/headshot.jpg"
defaults:
        # _Pages
        - scope:
                path: ""
                type: pages
        values:
                layout: single
                author_profile: true
defaults:
        #_Posts
        - scope:
                path: ""
                type: posts
        values:
                layout: single
                author_profile: true
                read_time: true
                comments: true
                share: true
                related: true
        paginate: 5
        paginate_path: /page:num/
include:
        - _Pages

